Repository SEAI-H-2020/Hardware-Documentation, pull requests merged in 2020-11, with the labels that each got.

#58 Finish ESP32-DevKitC-V4 transcription
  KiCAD/prototype/ESP32-DevKitC-V4.sch
Labels: Planning, documentation

#64 Correçao do bug no battery charger
  KiCAD/lib/Adafruit_BQ24074-rescue.dcm
  KiCAD/lib/Adafruit_BQ24074-rescue.lib
  KiCAD/lib/Grove-loudness sensor-rescue.dcm
  KiCAD/lib/Grove-loudness sensor-rescue.lib
  KiCAD/lib/sym-lib-table
  KiCAD/prototype/Adafruit_BQ24074-cache.lib
  KiCAD/prototype/Adafruit_BQ24074-rescue.dcm
  KiCAD/prototype/Adafruit_BQ24074-rescue.lib
  KiCAD/prototype/Adafruit_BQ24074.sch
  KiCAD/prototype/Adafruit_BQ24074.sch-bak
  KiCAD/prototype/Anemometer.sch
  KiCAD/prototype/BatteryCharger.sch
  KiCAD/prototype/BatteryCharger.sch-bak
  KiCAD/prototype/BuckConverter.sch
  KiCAD/prototype/DHT22.dcm
  KiCAD/prototype/DHT22.kicad_mod
  KiCAD/prototype/DHT22.lib
  KiCAD/prototype/DHT22.mod
  KiCAD/prototype/ESP32-DevKitC-V4-cache.lib
  KiCAD/prototype/ESP32-DevKitC-V4.sch
  KiCAD/prototype/ESP32-DevKitC-V4.sch-bak
  KiCAD/prototype/Grove-loudness sensor-cache.lib
  KiCAD/prototype/Grove-loudness sensor-rescue.dcm
  KiCAD/prototype/Grove-loudness sensor-rescue.lib
  KiCAD/prototype/Grove-loudness sensor.sch
  KiCAD/prototype/Grove-loudness sensor.sch-bak
  KiCAD/prototype/SoundSensor.sch
  KiCAD/prototype/buck_converter.sch-bak
  KiCAD/prototype/fp-info-cache
  KiCAD/prototype/prototype-cache.lib
  KiCAD/prototype/prototype.sch
  KiCAD/prototype/prototype.sch-bak
  KiCAD/prototype/sym-lib-table
  doc/Grove - Loudness Sensor Eagle/Grove-loudness sensor PCB.pdf
  doc/Grove - Loudness Sensor Eagle/Grove-loudness sensor.brd
  doc/Grove - Loudness Sensor Eagle/Grove-loudness sensor.sch
  doc/Grove - Loudness Sensor Eagle/Grove_loudness_sensor.pdf
Labels: bug

#72 Hotfix prototype
  KiCAD/prototype/BuckConverter.sch
  KiCAD/prototype/ESP32-DevKitC-V4.sch
Labels: bug

#70 Starting layout for the final shematics
  KiCAD/main/Adafruit_BQ24074.sch
  KiCAD/main/Anemometer.sch
  KiCAD/main/BatteryCharger.sch
  KiCAD/main/BuckConverter.sch
  KiCAD/main/Microcontroller.sch
  KiCAD/main/SoundSensor.sch
  KiCAD/main/main-cache.lib
  KiCAD/main/main.pro
  KiCAD/main/main.sch
  KiCAD/main/sym-lib-table
Labels: Planning

#74 Starting layout for the final shematics
  KiCAD/main/Adafruit_BQ24074.sch
  KiCAD/main/Anemometer.sch
  KiCAD/main/BatteryCharger.sch
  KiCAD/main/BuckConverter.sch
  KiCAD/main/Microcontroller.sch
  KiCAD/main/SoundSensor.sch
  KiCAD/main/main-cache.lib
  KiCAD/main/main.pro
  KiCAD/main/main.sch
  KiCAD/main/sym-lib-table
Labels: Planning

#75 Add missing local project footprint reference
  KiCAD/main/fp-lib-table
Labels: bug

#78 Add microcontroller stuff
  KiCAD/main/Adafruit_BQ24074.sch
  KiCAD/main/Anemometer.sch
  KiCAD/main/BuckConverter.sch
  KiCAD/main/Microcontroller.sch
  KiCAD/main/SoundSensor.sch
  KiCAD/main/fp-info-cache
  KiCAD/main/main-cache.lib
  KiCAD/main/main.sch
Labels: Planning

#79 Better track size and all connections done on preliminary pcb
  KiCAD/main/main.kicad_pcb
  KiCAD/main/main.pro
Labels: Planning

#80 Add example images for the PCB
  doc/Tests/main_pcb_1.png
  doc/Tests/main_pcb_2.png
  doc/Tests/main_pcb_3.png
Labels: documentation
